---
dependencies:
  - role: geerlingguy.swap
    vars:
      swap_file_size_mb: 2048
      swap_swappiness: 5
  - role: geerlingguy.security
    vars:
      security_ssh_permit_root_login: "yes"
      security_ssh_password_authentication: "no"
      security_fail2ban_enabled: off
