---
- name: Common configuration
  hosts: all
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  roles:
    - common

- name: Swarm manager
  hosts: managers
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  roles:
    - name: swarm-manager
      tags: swarm

