---
- name: Make sure stack directory is present
  file:
    path: /srv/site
    state: directory

- name: Make sure traefik configuration is actual
  template:
    src: templates/traefik.toml.j2
    dest: /srv/site/traefik.toml

- name: Make sure ingress network is up
  docker_network:
    name: traefiknet
    driver: overlay

- name: Deploy the main stack
  docker_stack:
    name: site
    resolve_image: never
    with_registry_auth: true
    compose:
      - version: "3.6"

        services:
          traefik:
            image: traefik:1.7.3
            ports:
              - "80:80"

            volumes:
              - /var/run/docker.sock:/var/run/docker.sock:ro
              - /srv/site/traefik.toml:/traefik.toml

            deploy:
              placement:
                constraints:
                  - node.hostname == {{ hostvars[groups['managers'][0]]['swarm_manager_hostname'] }}

            networks:
              - traefiknet

          periodic-prune:
            image: f213/periodic-docker-prune:1.1.1
            deploy:
              mode: global
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock

          logs:
            image: gliderlabs/logspout:v3.2.14
            command: "{{ log_destination }}"
            deploy:
              mode: global
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock



        networks:
          traefiknet:
            external: true
